                  <table class="table table-hover">
                    <tbody>
                      <tr>
                        <td>
                          <b>Name
                          </b>
                        </td>
                        <td>
                          <b>:
                          </b>
                        </td>
                        <td>Abhishek Rajput
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <b>Scholar Number
                          </b>
                        </td>
                        <td>
                          <b>:
                          </b>
                        </td>
                        <td>172120003
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <b>Branch
                          </b>
                        </td>
                        <td>
                          <b>:
                          </b>
                        </td>
                        <td>MCA
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <b>Year
                          </b>
                        </td>
                        <td>
                          <b>:
                          </b>
                        </td>
                        <td>First Year
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <b>Mobile Number
                          </b>
                        </td>
                        <td>
                          <b>:
                          </b>
                        </td>
                        <td>7770974841
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <b>Email Address
                          </b>
                        </td>
                        <td>
                          <b>:
                          </b>
                        </td>
                        <td>Larry@page.com
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <b>Date Of Birth
                          </b>
                        </td>
                        <td>
                          <b>:
                          </b>
                        </td>
                        <td>04/12/1998
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <b>Address
                          </b>
                        </td>
                        <td>
                          <b>:
                          </b>
                        </td>
                        <td>Zeckov live in a village
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <b>About me
                          </b>
                        </td>
                        <td>
                          <b>:
                          </b>
                        </td>
                        <td>Larry is a preofessional.
                        </td>
                      </tr>
                    </tbody>
                  </table>
